### PR TITLE
Add python and R demos

### PR DESCRIPTION
**Pull request by AlejandroCatalina**
Add python and R demos to a `demos` directory.

### CODE REVIEW

**Comment by avehtari** [comment]
There is a conflict in README.md. @AlejandroCatalina can you solve it?

**Comment by AlejandroCatalina** [comment]
Yes! I'll update this soon.

**Comment by AlejandroCatalina** [comment]
Updated @avehtari

**Comment by avehtari** [comment]
We decided to keep the demos in separate repos.

**Pull request closed without merging**
