### PR TITLE
Added additional hints for the lung cancer exercise (Assignment 1 question 3)

### PR DESCRIPTION
**Pull request by kunalghosh**
fixes:avehtari/bda_course#18

### CODE REVIEW

**Comment by avehtari** [comment]
Hi @kunalghosh , can you update exercises -> assignments. Sorry for the additional trouble.

**Comment by kunalghosh** [comment]
@avehtari did you fix this already as a part of the following commit ?

https://github.com/avehtari/BDA_course_Aalto/commit/280ba3df40e56cfbedae7b0776faebb7691d3cac#diff-a318350849486b149ca361e7b23b7677

based on the commit message.

**Comment by avehtari** [comment]
Maybe? Or Teemu?

**Comment by avehtari** [comment]
This pull request to master is including files that should only be in gh-pages. Making change to "Assignment 1 question 3" should not affect 105 files!

**Comment by avehtari** [comment]
Now 181 files changed. Maybe create a new PR?

**Comment by kunalghosh** [comment]
Yup, I somehow messed up the master of my fork. And this pull request is
just tracking the master. Will create a new one tomorrow.

**Comment by kunalghosh** [comment]
Created a new PR : https://github.com/avehtari/BDA_course_Aalto/pull/76
Closing this one now.

**Pull request closed without merging**
